import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    // justifyContent: "center",
    top: 80,
  },
  sendHoursContainer: {
    flex: 1,
    paddingTop: 40,
    paddingHorizontal: 20,
    // alignItems: "center",
    // justifyContent: "center",
  },
  itemStyle: {
    marginTop: 24,
    padding: 30,
    backgroundColor: "#DBE2EF",
    fontSize: 24,
  },
  itemStyleSmall: {
    fontSize: 14,
  },
  input: {
    // borderWidth: 1,
    // borderColor: "black",
    padding: 8,
    textAlign: "center",
    width: 300,
    // color: "white",
    fontSize: 24,
    marginBottom: 25,
    backgroundColor: "#DBE2EF",
    borderRadius: 15,
    color: "#112D4E",
  },
  button: {
    // borderWidth: 1,
    marginTop: 20,
    fontSize: 24,
    borderRadius: 7,
    padding: 8,
    // paddingHorizontal: 45,
    width: 300,
    textAlign: "center",
    backgroundColor: "#112D4E",
    color: "#F9F7F7",
    // borderColor: "black",
    // marginBottom: 160,
  },
  buttonSendHours: {
    // borderWidth: 1,
    marginTop: 5,
    marginBottom: 5,
    fontSize: 24,
    borderRadius: 30,
    paddingVertical: 14,
    paddingHorizontal: 20,
    backgroundColor: "#112D4E",
    alignItems: "center",
    justifyContent: "center",
    color: "#F9F7F7",
    // borderColor: "black",
  },
  modal: {
    backgroundColor: "#F9F7F7",
    borderRadius: 10,
  },
  optionOutsideArray: {
    alignItems: "center",
  },
  timePickerTextInside: {
    // alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginHorizontal: 6,
    marginVertical: 10,
    fontSize: 22,
    fontWeight: "bold",
    color: "#112D4E",
    backgroundColor: "#DBE2EF",
  },
  snackBar: {
    position: "absolute",
    width: "100%",
    bottom: 80,
    height: 70,
    // // alignItems: "baseline",
    // justifyContent: "flex-end",
  },
});
